version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: web_main
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_main
    ports:
      - 5431:5432
